### ISSUE TITLE
Nice implementation! Would you like to play?

### ISSUE THREAD

**Issue by rjcorwin** [bryanbraun/connect-four#6]
Hi @bryanbraun - Long time no see! I just ran into this on a Google search looking up the connect four clone I also made in JS. Figured I'd say hi :-). We should play Connect Four sometime! Hit the following invite URL in [Beaker Browser](https://beakerbrowser.com/) and send me the invite back!

dat://connect-four.hashbase.io/?join=02080684337b678b653ba3ec165cbf0787d2164e80c367d7d431e9d955eb7d68

**Comment by bryanbraun** [comment]
Hey, good to hear from you!

I hadn't heard of Beaker Browser before. I just downloaded it... looks interesting! I'll have to tinker with this a bit. :)

**Comment by rjcorwin** [comment]
Tara Vancil did a good job explaining the what and why of Beaker Browser at JSConf EU. Worth a watch if you are interested. https://www.youtube.com/watch?v=rJ_WvfF3FN8
