### ISSUE TITLE
No license; cannot legally use

### ISSUE THREAD

**Issue by Pikle2** [bryanbraun/connect-four#8]
Hello,

I love your project on Connect 4, but I can't legally use it because there isn't an open source license attached.

Could you please add a license you feel is appropriate to your repository?

Thanks!

**Comment by bryanbraun** [comment]
Thanks for the head's up, @mrpikle. I just added an MIT license file in [ee62db4](https://github.com/bryanbraun/connect-four/commit/ee62db41dc9b32a5e5ebf20b876809c9c3e0db6b).

Closing this now. 👍
